// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package ent

type NewUserInput struct {
	Name string `json:"name"`
}

type PaginationInput struct {
	After  *Cursor `json:"after"`
	Before *Cursor `json:"before"`
	First  *int    `json:"first"`
	Last   *int    `json:"last"`
}

type UserFilterInput struct {
	Name       *string          `json:"name"`
	Pagination *PaginationInput `json:"pagination"`
	Order      *UserOrder       `json:"order"`
}

type UserOps struct {
	New *User `json:"new"`
}
